#-*- coding:utf-8 -*-

list1 = [4,5,1,4,10,3,2,3,41,556,52,2,10]
for i in range(0,len(list1)):
	print(list1[i])

#Below code is same with upper code. it is more python style
for elem in list1:
	print(elem)

def makeTree():
	stageNum = 10
	for stage in range(stageNum):
		print("*"*i)


def whatIsComprehension():
	numOfElements = 10

	normalList = []
	for i in range(numOfElements):
		normalList.append(i)

	comprehensionList = [ i for i in range(numOfElements)]
	comprehensionSquareList = [i*i for i in range(numOfElements)]
	comprehensionEvenNumsList = [i for i in range(numOfElements) if i%2 == 0]

	# elements in each list objects are same
	# you can generate list using comprehesion in smarter, shorter way
	print(normalList)
	print(comprehensionList)
	print(comprehensionSquareList)
	print(comprehensionEvenNumsList)


	# Dict also can be generated by comprehension
	comprehensionDict = { key:key+10 for key in range(numOfElements) }
	print(comprehensionDict)

# Run the function below by erasing the first character '#' of each lines
#makeTree()
whatIsComprehension()